version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.6.0"
    TF_VARS_FILE: "stg.tfvars"

phases:
  install:
    commands:
      - apk update
      - apk add --no-cache curl unzip ca-certificates aws-cli jq
      - 'ARCH=$(uname -m); if [ "$ARCH" = "x86_64" ]; then TARCH=amd64; elif [ "$ARCH" = "aarch64" ]; then TARCH=arm64; else echo "Arquitetura não suportada: $ARCH"; exit 1; fi; URL="https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_${TARCH}.zip"; echo "Baixando Terraform de: $URL"; curl -fSLo terraform.zip "$URL"; unzip -o terraform.zip; install -m 0755 terraform /usr/local/bin/terraform; rm -f terraform terraform.zip; terraform -version'

  pre_build:
    commands:
      - echo "Assuming role for Staging deployment..."
      - TEMP_ROLE=$(aws sts assume-role --role-arn $STG_ROLE_ARN --role-session-name "pipeline-deploy-staging")
      - export AWS_ACCESS_KEY_ID=$(echo $TEMP_ROLE | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_ROLE | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $TEMP_ROLE | jq -r '.Credentials.SessionToken')

  build:
    commands:
      - TF_DIR="${CODEBUILD_SRC_DIR_TerraformSource}/${CODE_SRC_DIR}"
      - terraform -chdir="$TF_DIR" apply -input=false -auto-approve "${CODEBUILD_SRC_DIR_PlanStagingOutput}/tfplan-stg"
      - 'printf "Apply OK at %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > apply_done.txt'

  post_build:
    commands:
      - echo "Deploy to Staging completed on `date`"

artifacts:
  files:
    - apply_done.txt
  discard-paths: no
  name: ApplyOutput