version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y curl unzip jq ca-certificates python3 python3-pip
      
      # Install AWS CLI
      - |
        if yum install -y awscli >/dev/null 2>&1; then
          echo "aws-cli instalado via yum";
        else
          echo "aws-cli não disponível no yum; usando pip";
          pip3 install --no-cache-dir awscli;
        fi
      - aws --version
      
      # Install Terraform CLI
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      
  build:
    commands:
      - echo "Build phase started on `date`"
      
      # Validate Staging Environment
      - echo "Validating Staging environment..."
      - terraform init -backend-config=backend/backend-stg.hcl
      - terraform plan -var-file="envs/stg.tfvars" -out=tfplan-stg      
      
  post_build:
    commands:
      - echo "Post-build phase completed on `date`"

artifacts:
  files:
    - tfplan-stg 
    - .terraform/**/*
  discard-paths: no