version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - dnf install -y unzip jq wget --allowerasing
      - pip3 install --no-cache-dir awscli
      - aws --version

      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "=== PRE-BUILD APPLY STG ==="
      - echo "--- LISTING FILES RECEIVED ---"
      - ls -R

      - echo "--- DEBUG: Searching for tfplan-stg ---"
      - find . -maxdepth 3 -name "tfplan-stg"

      - echo "Reinitializing Terraform..."
      - terraform init -backend-config=backend/backend-stg.hcl

  build:
    commands:
      - echo "Deploy to Staging started on `date`"
      - echo "Assuming role to STG..."

      - |
        TEMP_ROLE=$(aws sts assume-role --role-arn $STG_ROLE_ARN --role-session-name pipeline-deploy-staging)
        export AWS_ACCESS_KEY_ID=$(echo $TEMP_ROLE | jq -r '.Credentials.AccessKeyId')
        export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_ROLE | jq -r '.Credentials.SecretAccessKey')
        export AWS_SESSION_TOKEN=$(echo $TEMP_ROLE | jq -r '.Credentials.SessionToken')

      - echo "Applying plan..."
      - terraform apply -auto-approve tfplan-stg

      - echo "OK" > apply_done.txt

  post_build:
    commands:
      - echo "Apply completed on `date`"

artifacts:
  files:
    - apply_done.txt
  discard-paths: no
  name: apply-output
