version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - dnf install -y unzip jq wget --allowerasing
      
      # Install AWS CLI
      - pip3 install --no-cache-dir awscli
      - aws --version
      
      # Install Terraform CLI
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      
  build:
    commands:
      - echo "Build phase started on `date`"
      
      # Validate Staging Environment
      - echo "Validating Staging environment..."
      - terraform init -backend-config=backend/backend-stg.hcl
      - terraform plan -var-file="envs/stg.tfvars" -out=tfplan-stg      
      
  post_build:
    commands:
      - echo "Post-build phase completed on `date`"

artifacts:
  files:
    - tfplan-stg
    - .terraform/**/*
    - .terraform.lock.hcl
  name: tfplan-artifact
  discard-paths: no