version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - dnf update -y
      - dnf install -y curl unzip jq ca-certificates python3 python3-pip wget
      
      # Install AWS CLI
      - pip3 install --no-cache-dir awscli
      - aws --version
      
      # Install Terraform CLI
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      
  build:
    commands:
      - echo "Build phase started on `date`"
      
      # Validate Production Environment
      - echo "Validating Production environment..."
      - terraform init -backend-config=backend/backend-prod.hcl
      - terraform plan -var-file="envs/prod.tfvars" -out=tfplan-prod      
      
  post_build:
    commands:
      - echo "Post-build phase completed on `date`"

artifacts:
  files:
    - tfplan-prod
    - .terraform/**/*
  discard-paths: no